### ISSUE TITLE
request

### ISSUE THREAD

**Issue by rodomb** [jethome-iot/rtl88x2cs#12]
Hi, 
I would like to use your code.
I am noob. Can you point me up, give some links.
How can I start, how use this code??

BR
nOOB

**Comment by adeepn** [comment]
You need the kernel source and toolchain. You can integrate it to kernel source like armbian https://github.com/armbian/build/blob/4fd0e0c29d3f8e58c182f6c5042307bbb15163b2/lib/functions/compilation/patch/drivers_network.sh#L409
or use as package like buildroot https://github.com/buildroot/buildroot/tree/master/package/rtl8822cs
